global:
  storageClass: gp2

auth:
  username: admin
  password: admin

replicaCount: 1

service:
  type: ClusterIP
  ports:
    amqp: 5672
    manager: 15672

metrics:
  enabled: true

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 256Mi
